### ISSUE TITLE
pod installation

### ISSUE THREAD

**Issue by devmsh** [electricbolt/bindkit#1]
Hi!

Thanks for your powerful and simple approach! we really like it and need to use it in our systems, is there any plan to support pod installation?

**Comment by electricbolt** [comment]
Sure, sounds like a perfectly reasonable request. I take it you want cocoapods rather than carthage?

**Comment by devmsh** [comment]
Yes

**Comment by electricbolt** [comment]
Hi, this should be complete now. Add `pod 'BindKit'` to your existing **Podfile**, and then run `pod install` from terminal. Let me know if I can close this issue. Thanks.

**Comment by devmsh** [comment]
[!] Unable to find a specification for `BindKit`

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tdd' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tdd
  pod 'BindKit'
  
  target 'tddTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tddUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

and run `pod install`

**Comment by electricbolt** [comment]
I believe you need to update your local cocoapods repository to pull down all the latest pod specs (including BindKit).

Try `pod repo update`
